plugins:
- config:
    content_type: application/json
    custom_fields_by_lua:
      streams: local ts=string.format('%18.0f', os.time()*1000000000) local log_payload
        = kong.log.serialize() local service = log_payload['service'] or 'noService' local cjson
        = require "cjson" local payload_string = cjson.encode(log_payload) local t
        = { {stream = {gateway='kong-gateway', service=service['name']}, values={{ts,
        payload_string}}} } return t
    flush_timeout: 2
    headers: {}
    http_endpoint: http://loki.mt.svc.cluster.local:3100/loki/api/v1/push
    keepalive: 60000
    method: POST
    queue_size: 1
    retry_count: 10
    timeout: 10000
  enabled: true
  name: http-log
  protocols:
  - grpc
  - grpcs
  - http
  - https
